language: objective-c
xcode_sdk: macosx10.11
osx_image: xcode7

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - LANGUAGE=en_US.UTF-8

install:
  - bash script/bootstrap

script:
  - bash script/build

before_deploy:
  - bash script/package
